config/routes.rb
Rails.application.routes.draw do
  mount AttachmentUploader.upload_endpoint(:cache) => "/images/upload"

  devise_for :admins, controllers: {
    sessions: 'admin/devise/sessions'
  }

  devise_for :users, controllers: {
    passwords: 'user/devise/passwords',
    registrations: 'user/devise/registrations',
    sessions: 'user/devise/sessions'
  }

  # landing page
  get 'public_page/landing_page', as: 'landing_page'
  root 'public_page#landing_page'

  # public page
  get 'events/:event_id' => 'public_page#show_event', as: 'show-events'
  get 'scan_physical_ticket/events/:event_id/link/:link_token' => 'public_page#scan_physical_ticket', as: 'scan_physical_ticket'
  get 'page_not_found' => 'public_page#page_not_found', as: 'page_not_found'
  get 'print_certification/:ticket_id' => 'public_page#print_certification', as: 'print_certification'

  resources :tickets, only: [] do
    resources :certification, only: [:index]
  end

  extend UserRoutes
  extend AdminRoutes
  extend Api::Routes
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue

  has_many   :ticket_stocks,    dependent: :destroy
  has_many   :event_sessions,   dependent: :destroy
  has_many   :tickets,          dependent: :destroy
  has_many   :ticket_sessions,  dependent: :destroy
  has_many   :images,           dependent: :destroy, as: :uploadable, class_name: "Image"

  validates_presence_of :name, :description

  accepts_nested_attributes_for :images, allow_destroy: true

  before_destroy :check_purchased_tickets

  scope :event_opened, -> { where(ticket_start_selling: true) }
  scope :order_start_time, -> { order(:start_time) }

  ransacker :start_time_filter do |parent|
    Arel.sql("date(start_time)")
  end

  def date_period
    "#{start_time.strftime('%d/%m/%Y %l:%M%p')} - #{end_time.strftime('%d/%m/%Y %l:%M%p')}"
  end

  def venue_location
    venue&.name || "-"
  end

  def is_started?
    return false if start_time.blank? || end_time.blank?
    return Time.zone.now.between?(start_time-60.minutes, end_time+120.minutes)
  end

  def is_ended?
    return false if end_time.blank?
    return Time.zone.now > end_time
  end

  def time_before_start
    time = (self.start_time - Time.zone.now)/60
    if time < 31
      time.to_i
    else
      0
    end
  end

  def go_to_platform_url
    if platform_url.include?("://")
      platform_url
    else
      "//"+platform_url
    end
  end

  def selling_status
    return "Ticket sales have not started" unless ticket_start_selling
    return "Yes, display it on the user page for sale"
  end

  def check_purchased_tickets
    if OrderItem.where(event: self).present?
      self.errors.add(:base, "You don't allowed to delete this event!")
      throw(:abort)
    end
  end

  def self.update_event_to_close
    events = Event.order(created_at: :DESC)

    events.each do |event|
      event.update(ticket_start_selling: false) if Time.zone.now >= event.end_time
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseAdminController
  include Modules::Crudable
  include Modules::GivenParamsFileable

  before_action :form_collection, only: %i[new edit create update index]
  before_action :set_search, only: %i[index]
  before_action :set_breadcrumb

  self.additional_parameters = [
    images_attributes: %i[image _destroy id]
  ]

  def index
    @name_page = "Event Data"
    @events    = @events.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    super do
      breadcrumb "New Event", "#"
    end
  end

  def edit
    super do
      breadcrumb "Event Details", admin_event_path(@event)
      breadcrumb "Edit Event", "#"
    end
  end

  def show
    super do
      @name_page = "Event Details"
      breadcrumb @name_page, admin_event_path(@event)

      @tab = params[:tab] || 'event-overview'
      ticket_stocks  if @tab.eql?('ticket-stock')
      event_sessions if @tab.eql?('event-session')

      @images = @event.images
    end
  end

  def destroy
    if @event.destroy
      flash[:notice] = "Event deleted successfully."
    else
      flash[:alert] = "You don't allowed to delete this event!"
    end
    redirect_to admin_events_path, status: :see_other and return
  end

  def ticket_stocks
    @stocks = @event.ticket_stocks
  end

  def event_sessions
    @event_sessions = @event.event_sessions
  end

  def set_search
    params[:q] ||= {}

    if params[:date_range].present?
      split_date = params[:date_range].split(" - ")
      params[:q][:start_time_gteq] = Date.strptime(split_date.first, '%d/%m/%Y').beginning_of_day
      params[:q][:start_time_lteq] = Date.strptime(split_date.last, '%d/%m/%Y').end_of_day
    end

    @q      = Event.ransack(params[:q])
    @events = @q.result.order_start_time
  end

  private

  def form_collection
    @venues        = build_select_options(Venue.all)
  end

  def set_breadcrumb
    default_breadcrumb
    breadcrumb "Event Data", :admin_events_path
  end
end

app/controllers/user/events_controller.rb
class User::EventsController < User::BaseController
  before_action :get_events, only: :index
  before_action :get_search_collection, only: :index
  before_action :set_breadcrumb

  def index
    @name_page = 'Event Lists'
    @events    = @events.order_start_time.page(params[:page])
  end

  def show
    @name_page = 'Event Details'
    @event     = Event.find(params[:id])
    breadcrumb @event.name, user_event_path(@event)

    @ticket_stocks  = @event.ticket_stocks.live
    @cart_preview   = current_user.cart
  end

  private

  def get_events
    params[:q] ||= { ticket_start_selling_eq: true }

    @q      = Event.includes(:ticket_stocks).ransack(params[:q])
    @events = @q.result
  end

  def get_search_collection
    @select_status = [['All', ''],['Opened', true],['Closed', false]]
  end

  def set_breadcrumb
    default_breadcrumb
    breadcrumb "Event Lists", :user_events_path
  end
end

app/views/admin/events/edit.html.erb
<%= render 'layouts/shared/breadcrumb' %>
<section class="section">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Edit Event</h5>
          <%= render partial: "admin/events/partials/form",locals:
              { event: @event,
                venues: @venues,
                url: admin_event_path(@event) } %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/events/index.html.erb
<%= render 'layouts/shared/breadcrumb' %>
<section class="section">
  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'admin/events/partials/search' %>
      <div class="card">
        <div class="card-body">
          <div class="d-flex">
            <div class="col-md-6">
              <h5 class="card-title">Event Data</h5>
            </div>
            <div class="col-md-6 mt-2" align="right">
              <%= link_to new_admin_event_path, class: 'btn btn-success mb-4' do %>
                <i class='zmdi zmdi-plus-circle'></i>
                New Event
              <% end %>
            </div>
          </div>
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col" width="30%">Name</th>
                <th scope="col">Venue / Platform</th>
                <th scope="col">Time Period</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @events.each_with_index do |event, idx| %>
                <tr>
                  <th scope="row"><%= idx+1 %></th>
                  <td><%= event.name %></td>
                  <td><%= event.venue.name %></td>
                  <td><%= event.date_period %></td>
                  <td>
                    <div class="dropdown">
                      <button class="nav-item dropdown pe-3 btn btn-secondary">
                        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                          <span class="d-none d-md-block dropdown-toggle ps-2">Action</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                          <li>
                            <%= link_to admin_event_path(event), class: "dropdown-item d-flex align-items-center" do %>
                              <i class="zmdi zmdi-eye"></i><span>Details</span>
                            <% end %>
                            <%= link_to edit_admin_event_path(event), class: "dropdown-item d-flex align-items-center" do %>
                              <i class="zmdi zmdi-edit"></i>Edit
                            <% end %>
                            <%= link_to admin_event_path(event),
                                data: { method: :delete, confirm: 'Are you sure?' },
                                class: "dropdown-item d-flex align-items-center" do %>
                              <i class="zmdi zmdi-delete"></i><span>Delete</span>
                            <% end %>
                          </li>
                        </ul>
                      </button>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @events,  window: 2 %>
          <%= page_entries_info @events, entry_name: 'events' if @events.present? %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/events/new.html.erb
<%= render 'layouts/shared/breadcrumb' %>
<section class="section">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">New Event</h5>
          <%= render partial: "admin/events/partials/form",locals:
              { event: @event,
                venues: @venues,
                url: admin_events_path } %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/events/show.html.erb
<%= render 'layouts/shared/breadcrumb' %>
<section class="section event">
  <div class="row">
    <div class="col-xl-12">
      <div class="card">
        <div class="card-body pt-3">
          <ul class="nav nav-tabs nav-tabs-bordered">
            <li class="nav-item">
              <%= link_to "Overview", admin_event_path(tab: "event-overview"), class: "nav-link #{'active' if @tab.eql?("event-overview")}" %>
            </li>
            <li class="nav-item">
              <%= link_to "Ticket Stock", admin_event_path(tab: "ticket-stock"), class: "nav-link #{'active' if @tab.eql?("ticket-stock")}" %>
            </li>
            <li class="nav-item">
              <%= link_to "Event Session Management", admin_event_path(tab: "event-session"), class: "nav-link #{'active' if @tab.eql?("event-session")}" %>
            </li>
          </ul>
          <div class="tab-content pt-2">
            <div class="tab-pane fade <%= 'show active' if @tab.eql?("event-overview") %> event-overview" id="event-overview">
              <div align="right">
                <%= link_to edit_admin_event_path(@event), class: 'btn btn-info me-2' do %>
                  <i class='zmdi zmdi-edit'></i>
                  Edit
                <% end %>
              </div>
              <h5 class="card-title">Event Details</h5>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold">Event Name</div>
                <div class="col-lg-9 col-md-8"><%= @event.name %></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold">Description</div>
                <div class="col-lg-9 col-md-8"><%= @event.description.html_safe %></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold ">Date</div>
                <div class="col-lg-9 col-md-8"><%= @event.date_period %></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold">Ticket Start Selling</div>
                <div class="col-lg-9 col-md-8"><%= @event.selling_status %></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold">Speaker</div>
                <div class="col-lg-9 col-md-8"><%= @event.speaker %></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold">Venue</div>
                <div class="col-lg-9 col-md-8"><%= @event.venue&.name || "-" %></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold">Publish Date</div>
                <div class="col-lg-9 col-md-8"><%= date_formater(@event.published_date, '%d/%m/%Y %I:%M %p') %></div>
              </div>
              <div class="row mb-2">
                <div class="col-lg-3 col-md-4 label font-weight-bold">Images</div>
                <div class="row">
                  <%= "<div class='col-12'><p>-</p></div>".html_safe if @images.blank? %>
                  <% @images.each do |image| %>
                    <div class='col-3 mt-auto mb-2 list-img__images'>
                      <div class="img-box shadow">
                        <%= image_tag get_image_url(image, :small), class: 'w-100' if image.image_data? %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>

            <% if @tab.eql?("ticket-stock") %>
              <div class="tab-pane fade show active pt-3" id="ticket-stock">
                <%= render partial: "admin/events/partials/table_ticket_stocks", locals: {stocks: @stocks} %>
              </div>
            <% elsif @tab.eql?("event-session") %>
              <div class="tab-pane fade show active pt-3" id="event-session">
                <%= render partial: "admin/events/partials/table_event_sessions", locals: {event_sessions: @event_sessions} %>
              </div>
            <% end %>
          </div>
          <div class="card-footer" align="left">
            <%= link_to "Back", admin_events_path, class: "btn btn-outline-primary me-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>