config/routes.rb
Rails.application.routes.draw do
  mount AttachmentUploader.upload_endpoint(:cache) => "/images/upload"

  devise_for :admins, controllers: {
    sessions: 'admin/devise/sessions'
  }

  devise_for :users, controllers: {
    passwords: 'user/devise/passwords',
    registrations: 'user/devise/registrations',
    sessions: 'user/devise/sessions'
  }

  # landing page
  get 'public_page/landing_page', as: 'landing_page'
  root 'public_page#landing_page'

  # public page
  get 'events/:event_id' => 'public_page#show_event', as: 'show-events'
  get 'scan_physical_ticket/events/:event_id/link/:link_token' => 'public_page#scan_physical_ticket', as: 'scan_physical_ticket'
  get 'page_not_found' => 'public_page#page_not_found', as: 'page_not_found'
  get 'print_certification/:ticket_id' => 'public_page#print_certification', as: 'print_certification'

  resources :tickets, only: [] do
    resources :certification, only: [:index]
  end

  extend UserRoutes
  extend AdminRoutes
  extend Api::Routes
end

app/views/layouts/shared/_breadcrumb.html.erb
<div class="pagetitle">
  <h1><%= @name_page %></h1>
  <nav>
    <ol class="breadcrumb">
      <% breadcrumb_trail do |crumb| %>
        <li class="breadcrumb-item <%= crumb.current? ? "active" : "" %>">
          <%= link_to crumb.name, crumb.url, (crumb.current? ? {"aria-current" => "page"} : {}) %>
          <% unless crumb.current? %><% end %>
        </li>
      <% end %>
    </ol>
  </nav>
</div>

app/views/layouts/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this <%= resource.class.model_name.human.downcase %> from being saved:</h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/shared/_favicon.html.erb
<title>Seminar Website</title>
<%#= favicon_link_tag 'favicon.ico' %>

app/views/layouts/shared/_header.html.erb
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="<%= root_path %>" class="logo d-flex align-items-center">
      <%= image_tag "logo.png" %>
      <span class="d-none d-lg-block">T-n-S</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div><!-- End Logo -->
  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <li class="nav-item dropdown pe-3">
        <% full_name = current_admin.name.upcase %>
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <!-- <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle"> -->
          <span class="d-none d-md-block dropdown-toggle ps-2"><%= full_name %></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6><%= current_admin.email %></h6>
            <span><%= full_name %></span>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to admin_my_profile_index_path, class: "dropdown-item d-flex align-items-center" do %>
              <i class="bi bi-person"></i>
              <span>My Profile</span>
            <% end %>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to admin_account_setting_index_path, class: "dropdown-item d-flex align-items-center" do %>
              <i class="bi bi-gear"></i>
              <span>Account Settings</span>
            <% end %>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to destroy_admin_session_path,
                data: { method: :delete },
                class: "dropdown-item d-flex align-items-center" do %>
              <i class="bi bi-gear"></i>
              Sign Out
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/shared/_header_user.html.erb
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="<%= root_path %>" class="logo d-flex align-items-center">
      <%= image_tag "logo.png" %>
      <span class="d-none d-lg-block">T-n-S</span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div>
  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <li class="nav-item dropdown pe-3">
        <% full_name = current_user.user_profile.full_name&.upcase %>
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <!-- <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle"> -->
          <span class="d-none d-md-block dropdown-toggle ps-2"><%= full_name %></span>
        </a><!-- End Profile Iamge Icon -->
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6><%= current_user.email %></h6>
            <span><%= full_name %></span>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to user_my_profile_index_path, class: "dropdown-item d-flex align-items-center" do %>
              <i class="bi bi-person"></i>
              <span>My Profile</span>
            <% end %>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to user_account_setting_index_path, class: "dropdown-item d-flex align-items-center" do %>
              <i class="bi bi-gear"></i>
              <span>Account Settings</span>
            <% end %>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <%= link_to destroy_admin_session_path,
                data: { method: :delete },
                class: "dropdown-item d-flex align-items-center" do %>
                <i class="bi bi-gear"></i>
                <span>Sign Out</span>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/shared/_sidebar.html.erb
<aside id="sidebar" class="sidebar">
  <% con_param = params[:controller] %>
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <%= link_to admin_root_path, class: class_active(con_param, 'dashboard') do %>
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to admin_users_path, class: class_active(con_param, 'admin/users') do %>
        <i class="bi bi-grid"></i>
        <span>Users</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to admin_venues_path, class: class_active(con_param, 'admin/venues') do %>
        <i class="bi bi-grid"></i>
        <span>Venues</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to admin_events_path, class: class_active(con_param, 'admin/events') do %>
        <i class="bi bi-grid"></i>
        <span>Events</span>
      <% end %> 
    </li>
    <li class="nav-item">
      <%= link_to admin_orders_path, class: class_active(con_param, 'admin/orders') do %>
        <i class="bi bi-grid"></i>
        <span>Orders</span>
      <% end %> 
    </li>
    <li class="nav-item">
      <%= link_to admin_reportings_path, class: class_active(con_param, 'admin/reportings') do %>
        <i class="bi bi-grid"></i>
        <span>Reportings</span>
      <% end %> 
    </li>
<!--     <li class="nav-heading">Pages</li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="users-profile.html">
        <i class="bi bi-person"></i>
        <span>Profile</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-faq.html">
        <i class="bi bi-question-circle"></i>
        <span>F.A.Q</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-contact.html">
        <i class="bi bi-envelope"></i>
        <span>Contact</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-register.html">
        <i class="bi bi-card-list"></i>
        <span>Register</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-login.html">
        <i class="bi bi-box-arrow-in-right"></i>
        <span>Login</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-error-404.html">
        <i class="bi bi-dash-circle"></i>
        <span>Error 404</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link collapsed" href="pages-blank.html">
        <i class="bi bi-file-earmark"></i>
        <span>Blank</span>
      </a>
    </li> -->
  </ul>
</aside><!-- End Sidebar-->

app/views/layouts/shared/_sidebar_user.html.erb
<aside id="sidebar" class="sidebar">
  <% con_param = params[:controller] %>
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <%= link_to user_events_path, class: class_active(con_param, 'user/events') do %>
        <i class="bi bi-grid"></i>
        <span>Events</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to user_orders_path, class: class_active(con_param, 'user/orders')  do %>
        <i class="bi bi-grid"></i>
        <span>My Orders</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to user_tickets_path, class: class_active(con_param, 'user/tickets')  do %>
        <i class="bi bi-grid"></i>
        <span>My Tickets</span>
      <% end %>
    </li>
  </ul>
</aside>

app/views/layouts/shared/breadcrumb.html.erb
<div class="row">
  <div class="col-12">
    <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
      <div class="page_title_left">
        <h3 class="dark_text"><%= @name_page %></h3>
        <ol class="breadcrumb page_bradcam mb-0">
          <% breadcrumb_trail do |crumb| %>
            <li class="breadcrumb-item <%= crumb.current? ? "current" : "" %>">
              <%= link_to crumb.name, crumb.url, (crumb.current? ? {"aria-current" => "page"} : {}) %>
              <% unless crumb.current? %><% end %>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>