config/routes.rb
Rails.application.routes.draw do
  mount AttachmentUploader.upload_endpoint(:cache) => "/images/upload"

  devise_for :admins, controllers: {
    sessions: 'admin/devise/sessions'
  }

  devise_for :users, controllers: {
    passwords: 'user/devise/passwords',
    registrations: 'user/devise/registrations',
    sessions: 'user/devise/sessions'
  }

  # landing page
  get 'public_page/landing_page', as: 'landing_page'
  root 'public_page#landing_page'

  # public page
  get 'events/:event_id' => 'public_page#show_event', as: 'show-events'
  get 'scan_physical_ticket/events/:event_id/link/:link_token' => 'public_page#scan_physical_ticket', as: 'scan_physical_ticket'
  get 'page_not_found' => 'public_page#page_not_found', as: 'page_not_found'
  get 'print_certification/:ticket_id' => 'public_page#print_certification', as: 'print_certification'

  resources :tickets, only: [] do
    resources :certification, only: [:index]
  end

  extend UserRoutes
  extend AdminRoutes
  extend Api::Routes
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  include UrlChecker

  belongs_to :event
  belongs_to :ownership, class_name: "User", foreign_key: "ownership_id", optional: true
  belongs_to :order_item
  belongs_to :ticket_stock
  belongs_to :last_ticket_session, class_name: "TicketSession", foreign_key: "last_ticket_session_id", optional: true

  has_many   :ticket_sessions, dependent: :destroy

  serialize :api_response, Hash

  # validate  :all_tickets_generated

  scope :order_start_time, -> { includes(:event).order("event.start_time") }

  def all_tickets_generated
    return true if skip_ticket_validation
    if order_item.tickets.reload.count.to_i >= order_item.quantity.to_i
      errors.add(:base, 'All links has been registered')
      false
    end
  end

  def get_scan_ticket_alert(visitor_id)
    last_request_time = api_response[:last_request]&.to_datetime
    return {} if last_request_time.blank?

    return scan_ticket_msg(visitor_id) if (DateTime.now-3.minutes) <= last_request_time
    return {}
  end

  def scan_ticket_msg(visitor_id)
    current_time  = DateTime.now
    event_session = EventSession.current_event_session(event)
    last_session  = ticket_sessions.where("visitor_id_out =? OR visitor_id_in =?", visitor_id, visitor_id).
                    latest_visitor_sesions(event_session).first
    limit_time    = (current_time < (api_response[visitor_id][:last_updated].to_datetime + 2.minute)) rescue false
    data_response = api_response[visitor_id]

    if data_response.present? && limit_time
      failed_status = data_response[:status].eql?("failed")
      alert_label   = data_response[:status].eql?("success") ? "success" : failed_status ? "danger" : "warning"
      alert_msg     = failed_status ? "Scan In Failed!" : data_response[:message]
      return { alert_label: alert_label, alert_msg: alert_msg, failed_reason: (failed_status ? data_response[:message] : "") }
    else
      return {}
    end
  end

  def allow_print_certificate?
    ticket_sessions.scan_in_sessions.with_out_time.present?
  end

  def get_user_uid
    order_item.order.user.user_profile.user_uid rescue nil
  end

  # START CLASS METHOD
  class << self
    def generate_ticket(order_item, options = {})
      event           = order_item.ticket_stock.event
      remark          = options[:remark]
      ticket_arr      = []
      errors          = []
      ticket_attendee = []

      tickets_data = Ticket.where(order_item: order_item).order(:id)
      gen_total    = order_item.quantity.to_i - tickets_data.count

      gen_total.times do
        order   = order_item.order
        ticket  = TicketGenerator.create(event.id, order_item, {remark: remark})

        if ticket.errors.present?
          errors += ticket.errors.full_messages
        else
          link_index  = tickets_data.ids.find_index(ticket.id)+1
          split_email = ticket.ownership.email.split("@")
          fake_email  = "#{split_email.first}+tix00#{link_index}+#{ticket.id}@#{split_email.last}"
          ticket.update(fake_email: fake_email)
          ticket_arr << ticket
        end if ticket.present?
      end

      { tickets: ticket_arr, errors: errors }
    end
  end

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseAdminController
  before_action :get_event
  before_action :set_search
  before_action :set_breadcrumb

  def index
    @tickets = @tickets.page(params[:page])
  end

  def set_search
    params[:q] ||= {}

    @q       = Ticket.where(event_id: params[:event_id]).ransack(params[:q])
    @tickets = @q.result
  end

  private

  def set_breadcrumb
    default_breadcrumb
    breadcrumb "Event Data", :admin_events_path
    breadcrumb "Event Details", admin_event_path(@event, tab: "ticket-stock")
    breadcrumb "All Tickets", "#"
  end

  def get_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/user/tickets_controller.rb
class User::TicketsController < User::BaseController
  # include ApplicationHelper
  include Modules::TicketLinkAccess

  before_action :set_breadcrumb
  before_action :get_ticket_stock, only: [:details]
  before_action :get_ticket, only: [:edit_remark, :update_remark]

  def index
    @name_page = 'My Tickets'
    @tickets   = current_user.my_tickets.group(:ticket_stock).count
    @tickets   = Kaminari.paginate_array(@tickets.to_a).page(params[:page])
  end

  def details
    @name_page = 'Ticket Details'
    breadcrumb @name_page, ticket_details_user_tickets_path(@ticket_stock)

    @event   = @ticket_stock.event
    @venue   = @event.venue
    @tickets = current_user.my_tickets.where(ticket_stock: @ticket_stock)
  end

  def edit_remark
    respond_to do |format|
      format.js { }
    end
  end

  def update_remark
    if @ticket.update(ticket_params)
      flash[:notice] = 'Ticket Info successfully updated'
    else
      flash[:alert] = 'Failed to update Ticket Info'
    end

    respond_to do |format|
      format.js { }
      format.html { redirect_to ticket_details_user_tickets_path(@ticket.ticket_stock_id) }
    end
  end

  # def get_link
  #   order_item = OrderItem.find(params[:id])

  #   if order_item.inventory.event.online_event
  #     generated_link = Ticket.generate_ticket(order_item, current_user)

  #     links = generated_link[:links]
  #     errors = generated_link[:errors]
  #   else
  #     links = nil
  #   end

  #   if links.blank?
  #     flash[:alert] = 'Something went wrong. 0 link created.'
  #   else
  #     flash[:notice] = "#{helpers.pluralize(links.size, 'link')} has been created."
  #   end

  #   unless errors.blank?
  #     flash[:alert] = "#{errors.uniq.to_sentence}"
  #     flash[:alert] += ". #{helpers.pluralize(params[:quantity].to_i - links.size , 'link')} not created."
  #   end

  #   redirect_to user_ticket_url(params[:id])
  # end

  def check_ownership
    if !@ticket&.ownership_account&.eql?(current_account)
      flash[:alert] = 'Ticket not found!'
      redirect_to user_tickets_path and return
    end
  end

  private

  def set_breadcrumb
    default_breadcrumb
    breadcrumb 'My Tickets', :user_tickets_path
  end

  def get_ticket_stock
    @ticket_stock = TicketStock.find(params[:ticket_stock_id])
  end

  def get_ticket
    @ticket = Ticket.find_by(id: params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:id, :remark, :attendee_name)
  end
end

app/views/admin/tickets/index.html.erb
<%= render 'layouts/shared/breadcrumb' %>
<section class="section">
  <div class="row">
    <div class="col-lg-12">
      <%= render partial: 'admin/tickets/partials/search' %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">All Tickets Sold</h5>
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col">Ticket ID</th>
                <th scope="col">Ticket Code</th>
                <th scope="col">Ownership UID</th>
                <th scope="col">Ownership Name</th>
                <th scope="col">Attendee Name</th>
                <th scope="col">Remark</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @tickets.each_with_index do |ticket, idx| %>
                <tr>
                  <th scope="row"><%= idx+1 %></th>
                  <td>#<%= ticket.id %></td>
                  <td><%= ticket.link_token %></td>
                  <td><%= ticket.get_user_uid %></td>
                  <td><%= ticket.ownership&.user_profile&.full_name %></td>
                  <td><%= ticket.attendee_name %></td>
                  <td><%= ticket.remark %></td>
                  <td>
                    <% if ticket.allow_print_certificate? %>
                      <%#= link_to "Print Certificate", print_certification_path(ticket, format: "pdf"),
                        class: 'btn btn-info text-white', target: "_blank" %>
                      <%= link_to "Print Certificate", ticket_certification_index_path(ticket),
                        class: 'btn btn-info text-white', target: "_blank" %>
                    <% end  %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @tickets,  window: 2 %>
          <%= page_entries_info @tickets, entry_name: 'tickets' if @tickets.present? %>
        </div>
      </div>
    </div>
  </div>
</section>