config/routes.rb
Rails.application.routes.draw do
  mount AttachmentUploader.upload_endpoint(:cache) => "/images/upload"

  devise_for :admins, controllers: {
    sessions: 'admin/devise/sessions'
  }

  devise_for :users, controllers: {
    passwords: 'user/devise/passwords',
    registrations: 'user/devise/registrations',
    sessions: 'user/devise/sessions'
  }

  # landing page
  get 'public_page/landing_page', as: 'landing_page'
  root 'public_page#landing_page'

  # public page
  get 'events/:event_id' => 'public_page#show_event', as: 'show-events'
  get 'scan_physical_ticket/events/:event_id/link/:link_token' => 'public_page#scan_physical_ticket', as: 'scan_physical_ticket'
  get 'page_not_found' => 'public_page#page_not_found', as: 'page_not_found'
  get 'print_certification/:ticket_id' => 'public_page#print_certification', as: 'print_certification'

  resources :tickets, only: [] do
    resources :certification, only: [:index]
  end

  extend UserRoutes
  extend AdminRoutes
  extend Api::Routes
end

app/controllers/public_page_controller.rb
class PublicPageController < ApplicationController
  layout 'application_public_page'

  before_action :check_current_sign_in, only: :landing_page
  before_action :get_ticket, only: [:show_event, :scan_physical_ticket]
  before_action :get_event, only: [:show_event, :scan_physical_ticket]
  before_action :check_params_event, only: :show_event
  before_action :redirect_back, only: :scan_physical_ticket

  def landing_page
    if admin_signed_in?
      flash[:alert] = "You're already signed in as an Admin!"
      redirect_to admin_root_path and return
    elsif user_signed_in?
      flash[:alert] = "You're already signed in!"
      redirect_to user_root_path and return
    else
     redirect_to new_user_session_path and return
   end
  end

  def show_event
    @venue = @event.venue
    @ticket_stock = @ticket.ticket_stock
  end

  def scan_physical_ticket
    @event_session = EventSession.current_event_session(@event)
    @last_visitor_sesion = @ticket.ticket_sessions&.latest_visitor_sesions(@event_session).last
  end

  def print_certification
    @ticket  = Ticket.find(params[:ticket_id])
    template = "#{params[:controller]}/certification"

    respond_to do |format|
      format.pdf do
        render pdf: "certification.pdf",
              template: template,
                layout: "layouts/application",
         viewport_size: "1024x768",
          orientation: "Landscape"
      end
    end
  end

  private

  def check_current_sign_in
    if user_signed_in?
      flash[:alert] = "You are already signed in."
      redirect_to root_path
    end
  end

  def check_params_event
    if @event.blank? || @ticket.blank?
      redirect_page = user_signed_in? ? user_root_path : root_path
      redirect_to redirect_page, alert: 'Page Not Found!'
    end
  end

  def get_ticket
    @ticket = Ticket.find_by(link_token: params[:link_token])
  end

  def get_event
    @event  = Event.find_by(id: params[:event_id])
  end

  def redirect_back
    if @ticket.blank?
      flash[:alert] = "Not allowed to access scan ticket page! Invalid ticket link."
      redirect_to user_root_path and return if current_user.present?
      redirect_to show_events_path(@event) and return
    end
  end
end

app/views/public_page/certification.pdf.erb
<style type="text/css">
  @import url('https://fonts.googleapis.com/css?family=Open+Sans|Pinyon+Script|Rochester');

  .cursive {
    font-family: 'Pinyon Script', cursive;
  }

  .sans {
    font-family: 'Open Sans', sans-serif;
  }

  .bold {
    font-weight: bold;
  }

  .block {
    display: block;
  }

  .underline {
    border-bottom: 1px solid #777;
    padding: 5px;
    margin-bottom: 15px;
  }

  .margin-0 {
    margin: 0;
  }

  .padding-0 {
    padding: 0;
  }

  .pm-empty-space {
    height: 40px;
    width: 100%;
  }

/*  body {
    padding: 20px 0;
    background: #ccc;
  }*/

  * {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
  }

  .wrapper-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
  }

  .container {
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
  }

  .outer-border {
    width: 794px;
    height: 594px;
    position: absolute;
    left: 50%;
    margin-left: -397px;
    top: 50%;
    margin-top:-297px;
    border: 2px solid #fff;
  }
  
  .inner-border {
    width: 730px;
    height: 530px;
    position: absolute;
    left: 50%;
    margin-left: -365px;
    top: 50%;
    margin-top:-265px;
    border: 2px solid #fff;
  }

  .pm-certificate-container {
    position: relative;
    width: 800px;
    height: 600px;
    background-color: #618597;
    padding: 30px;
    color: #333;
    font-family: 'Open Sans', sans-serif;
    box-shadow: 0 0 5px rgba(0, 0, 0, .5);
    background: -webkit-repeating-linear-gradient(
      45deg,
      #618597,
      #618597 1px,
      #b2cad6 1px,
      #b2cad6 2px
    );
    background: repeating-linear-gradient(
      90deg,
      #618597,
      #618597 1px,
      #b2cad6 1px,
      #b2cad6 2px
    );
    }

    .pm-certificate-border {
      position: relative;
      width: 720px;
      height: 520px;
      padding: 0;
      border: 1px solid #E1E5F0;
      background-color: rgba(255, 255, 255, 1);
      background-image: none;
      left: 50%;
      margin-left: -360px;
      top: 50%;
      margin-top: -260px;

      .pm-certificate-block {
        width: 650px;
        height: 200px;
        position: relative;
        left: 50%;
        margin-left: -325px;
        top: 70px;
        margin-top: 0;
      }
    }

    .pm-certificate-header {
      margin-bottom: 10px;
    }

    .pm-certificate-title {
      position: relative;
      top: 40px;

      h2 {
        font-size: 34px !important;
      }
    }

    .pm-certificate-body {
      padding: 20px;

      .pm-name-text {
        font-size: 20px;
      }
    }

    .pm-earned {
      margin: 15px 0 20px;
      .pm-earned-text {
        font-size: 20px;
      }
      .pm-credits-text {
        font-size: 15px;
      }
    }

    .pm-course-title {
      .pm-earned-text {
        font-size: 20px;
      }
      .pm-credits-text {
        font-size: 15px;
      }
    }

    .pm-certified {
      font-size: 12px;

      .underline {
        margin-bottom: 5px;
      }
    }

    .pm-certificate-footer {
      width: 650px;
      height: 100px;
      position: relative;
      left: 50%;
      margin-left: -325px;
      bottom: -105px;
    }
</style>

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
</head>
<body>
  <div class="container pm-certificate-container">
    <div class="outer-border"></div>
    <div class="inner-border"></div>
    
    <div class="pm-certificate-border col-xs-12">
      <div class="row pm-certificate-header">
        <div class="pm-certificate-title cursive col-xs-12 text-center">
          <h2>Buffalo Public Schools Certificate of Completion</h2>
        </div>
      </div>

      <div class="row pm-certificate-body">
        
        <div class="pm-certificate-block">
            <div class="col-xs-12">
              <div class="row">
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
                <div class="pm-certificate-name underline margin-0 col-xs-8 text-center">
                  <span class="pm-name-text bold">TrueNorth Administrator</span>
                </div>
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
              </div>
            </div>          

            <div class="col-xs-12">
              <div class="row">
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
                <div class="pm-earned col-xs-8 text-center">
                  <span class="pm-earned-text padding-0 block cursive">has earned</span>
                  <span class="pm-credits-text block bold sans">PD175: 1.0 Credit Hours</span>
                </div>
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
                <div class="col-xs-12"></div>
              </div>
            </div>
            
            <div class="col-xs-12">
              <div class="row">
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
                <div class="pm-course-title col-xs-8 text-center">
                  <span class="pm-earned-text block cursive">while completing the training course entitled</span>
                </div>
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
              </div>
            </div>

            <div class="col-xs-12">
              <div class="row">
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
                <div class="pm-course-title underline col-xs-8 text-center">
                  <span class="pm-credits-text block bold sans">BPS PGS Initial PLO for Principals at Cluster Meetings</span>
                </div>
                <div class="col-xs-2"><!-- LEAVE EMPTY --></div>
              </div>
            </div>
        </div>       
        
        <div class="col-xs-12">
          <div class="row">
            <div class="pm-certificate-footer wrapper-grid">
              <div class="col-xs-4 pm-certified col-xs-4 text-center">
                <span class="pm-credits-text block sans">Buffalo City School District</span>
                <span class="pm-empty-space block underline"></span>
                <span class="bold block">Crystal Benton Instructional Specialist II, Staff Development</span>
              </div>
              <div class="col-xs-4 pm-certified col-xs-4 text-center">
                <span class="pm-credits-text block sans">Date Completed</span>
                <span class="pm-empty-space block underline"></span>
                <span class="bold block">DOB: </span>
                <span class="bold block">Social Security # (last 4 digits)</span>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </div>
</body>
</html>

app/views/public_page/landing_page.html.erb
<div id="loginform">
  <div class="logo">
    <h3 class="db">
      User Login
    </h3>
    <h5 class="font-medium m-b-20">Sign In</h5>
  </div>
  <div class="row">
    <div class="col-12">
      <% if alert %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
          <%= alert %>
        </div>
      <% end %>
      <%= form_for(@resource, as: @resource_name, url: session_path(@resource_name)) do |f| %>
        <%= render "devise/shared/error_messages", resource: @resource %>
        
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="zmdi zmdi-account-o"></i></span>
          </div>
          <%= f.email_field :email, autofocus: true, autocomplete: :off, class: "form-control form-control-lg", placeholder: "Email" %>
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="zmdi zmdi-lock-outline"></i></span>
          </div>
          <%= f.password_field :password, autofocus: true, autocomplete: "current-password", class: "form-control form-control-lg", placeholder: "Enter password" %>
        </div>

<!--         <div class="form-group row">
          <div class="col-md-12">
            <div class="custom-control custom-checkbox">
              <%# if devise_mapping.rememberable? %>
                <%#= f.check_box :remember_me, class: "custom-control-input", id: "rememberMe" %>
                <label class="custom-control-label" for="rememberMe">Remember me</label>
              <%# end %>
            </div>
          </div>
        </div> -->
        <div class="form-group m-0 text-center">
          <div class="col-xs-12">
            <%= f.submit "Log in", class: "btn btn-block btn-lg btn-info" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/public_page/page_not_found.html.erb
<div class="jumbotron text-center">
  <h1 class="display-3">Page Not Found!</h1>
  <p class="lead"><strong><%#= alert %></strong></p>
  <p class="lead"><strong>Please contact TQG Admin</strong> for further instructions.</p>
</div>

app/views/public_page/scan_physical_ticket.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script>
<div class="physical-ticket w-100">
  <div class="physical-ticket__item w-25 m-auto">
    <div class="physical-ticket__title-qrcode text-center mb-3">
      <h4 class="font-weight-bolder">Show this QR code to scan your attendance!</h4>
    </div>
    <div class="physical-ticket__event-info w-100 bg-info rounded mb-3">
      <p class="text-center text-white">Event info</p>
    </div>
    <div class="physical-ticket__qrcode-wrap bg-white rounded shadow-sm">
      <div class="physical-ticket__qrcode mb-3">
        <div id="ticket-id" data-ticket-id="<%= @ticket.id %>"></div>
        <div id="qrcode"></div>
      </div>
      <% last_ticket_session  = @ticket.last_ticket_session %>
      <div id="param-refresh" data-param-refresh="<%= params[:refresh] %>"></div>
      <div class="alert-wrapper hide">
        <div class="physical-ticket__alert px-2">
          <div class="ticket-alert-label alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close" data-bs-dismiss="alert"><span aria-hidden="true"></span></button>
            <div id="error_explanation">
              <p class="ticket-alert-text"></p>
            </div>
          </div>
        </div>
        <div class="physical-ticket__title mb-3 failed-reason" style="padding-left: 10px;"></div>
      </div>
      <div class="physical-ticket__title text-center mb-3">
        <h4 class="font-weight-bolder"><%= @event.name %></h4>
        <h6><%= @event.date_period %></h6>
        <h6><%= @event.venue&.name %></h6>
        <h6 class="mb-3 font-weight-bolder"><%= @event_session&.title %></h6>
        <h6><%= @ticket.attendee_name %></h6>
        <%= link_to 'Refresh', scan_physical_ticket_path(@ticket.event, @ticket.link_token, refresh: true), class: 'btn btn-primary mt-2' %>
      </div>
      <% scan_in = @last_visitor_sesion.blank? ? 'empty' : 'checked bg-success' %>
      <div class="physical-ticket__status-<%= scan_in %> w-100 text-center mb-3">
        <p class="text-white font-weight-bold">Ticket No: <%= @ticket.id %></p>
        <% if last_ticket_session.present? %>
          <p class="text-white font-weight-bold">Last Scan In: <%= date_formater(last_ticket_session.in_time, '%d/%m/%Y %I:%M %p') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :custom_js_tag do %>
<script>
  $(document).ready(function() {
    var ticketId = $('#ticket-id').attr('data-ticket-id');
    var refresh  = $('#param-refresh').attr('data-param-refresh');

    const fpPromise = import('https://openfpcdn.io/fingerprintjs/v3')
      .then(FingerprintJS => FingerprintJS.load())

    // Get the visitor identifier when you need it.
    fpPromise
      .then(fp => fp.get())
      .then(result => {
        // This is the visitor identifier:
        visitorId = result.visitorId
        console.log(ticketId)
        console.log(visitorId)
        callCreateQrCode(ticketId, visitorId);
        callTicketAlert(ticketId, visitorId, refresh);
        var btoa_title_qrcode = btoa($('#qrcode').attr('title'))
        $('#qrcode').attr('title', btoa_title_qrcode)
      })
      .catch(error => console.error(error))

  });
</script>
<% end %>

app/views/public_page/show_event.html.erb
<main id="main" class="main">
  <section class="section profile">
    <div class="row">
      <div class="col-xl-7">
        <div class="card">
          <div class="card-body event-card pt-4 d-flex flex-column align-items-center">
            <% default_img = get_image_url(@event.images&.first, :medium) rescue nil %>
            <%= image_tag(default_img, class: 'w-100 card-img-top') %>
            <h2 class="mt-4"><%= @event.name %></h2>
          </div>
          <div class="card-body profile-card pt-4 d-flex flex-column">
            <%= @event.description.html_safe %>
          </div>
        </div>
      </div>

      <div class="col-xl-5">
        <div class="card">
          <div class="card-body pt-3">
            <div class="tab-content pt-2">
              <div class="tab-pane fade show active profile-overview" id="profile-overview">
                <h5 class="card-title" style="font-size: 24px!important;"><%= @event.name %></h5>
                <!-- <p class="small"><%#= @event.date_period %></p> -->
                <div class="row">
                  <div class="col-lg-3 col-md-4 label ">Date & Time</div>
                  <div class="col-lg-9 col-md-8"><%= @event.date_period %></div>
                </div>
                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Location</div>
                  <div class="col-lg-9 col-md-8"><%= @event.venue_location %></div>
                </div>
                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Speaker</div>
                  <div class="col-lg-9 col-md-8"><%= @event.speaker %></div>
                </div>
                <div class="row">
                  <div class="col-lg-3 col-md-4 label">Scan QR Link</div>
                  <div class="col-lg-9 col-md-8">
                      <span class="schedule__detail-content">
                        <%= link_to "User Attendance", link_user_ticket_path(@ticket, @ticket.link_token) rescue "-" %><br><br>
                        <%= link_to 'Refresh', show_events_path(@event, link_token: params[:link_token]), class: "btn btn-primary mb-2" %>
                      </span>
                    
                    <% if !@event.time_before_start.eql?(0) %>
                      <% if @event.time_before_start > 29 %>
                        <div class="alert alert-danger" role="alert">
                          Event will start in <%= @event.time_before_start-29 %> minutes.
                        </div>
                      <% else %>
                        <% if @event.is_started? %>
                          <div class="alert alert-success" role="alert">
                            Event already started. Please Scan QR Link.
                          </div>
                        <% end %>
                      <% end %>
                    <% else %>
                      <div class="alert alert-danger" role="alert">
                        Event will start on time, please refresh this page 1 hour prior the event.
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>